### ISSUE TITLE
Track KPIs and OKR

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#11]
Have been tracking metrics [in this spreadsheet](https://docs.google.com/spreadsheets/d/1pXJS9ElFFuJ3BaSIWhOJrVMIXlu_s0tN1wTsUV7IJyY/edit#gid=0) on a weekly basis.
Zanete might start tracking them differently [in this overview file](https://docs.google.com/spreadsheets/d/19jBO9WdZ7lOQ2R2bi7QOZMsRG6oIBDX2FWV1Q6mW1mg/edit#gid=0).

![Image](https://user-images.githubusercontent.com/100846607/206739994-16015cba-e0de-428d-aaba-754eebf20175.png)

**Comment by tadanna** [comment]
@holanita well received! I will try this out next Monday and let you know if I have questions

**Comment by tadanna** [comment]
thanks @holanita I managed to work on it. I have some doubts tho: 

- on the meetup dashboard it gives a total of 96 events in the past, but if I follow the link in the sheet it lists 100 events. What is correct?
- I am not sure about the patterns metrics. I have used the number of open issues for the last 2, but the first it's an empty wiki page. Can you explain?
- I don't have access to the Google doc for the trainings, I have just requested it then I'll be able to see if I have doubts there.

**Comment by tadanna** [comment]
@holanita if I go on the dashboard I also see 96, but from the event page it shows 100 - see screenshot: 
<img width="1405" alt="Screenshot 2023-02-21 at 10 22 23" src="https://user-images.githubusercontent.com/122878451/220318237-fb3a1cb0-92c7-4d77-b627-9b1bf88d2cbf.png">
