### ISSUE TITLE
Graphic for Copenhagen Events

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#117]
Hi @jenya-design

Copenhagen has a weekly meetup. Currently for their event graphic they are using their own design. Could you help us 'rethink' this graphic to fit in with GSF branding and be exciting?

https://www.meetup.com/gsf-copenhagen/events/295657175/

**Comment by Jenya-design** [comment]
@adamj89  please check the update attached and[ in Canva](https://www.canva.com/design/DAFuh_IhDzM/AFM1rCqRxvbX4XhyURGD_w/edit?utm_content=DAFuh_IhDzM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)


![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/f01dca9a-80f0-4331-baa9-6180e4a52712)


![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/7b5e6dfc-ab22-4148-84f3-d6a00bca94e5)
