### ISSUE TITLE
Update milestones along the way

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#12]
Milestones last updated today / Jan 18:
[Admin/Ongoing](https://github.com/Green-Software-Foundation/meetup/milestone/1)
No due date. **Ongoing.**  
[M1 [Dec-31] Project Setup](https://github.com/Green-Software-Foundation/meetup/milestone/2)
Past due by 18 days  Last updated less than a minute ago. **100% complete.**
[M2 [March-31] Planning & Preparation](https://github.com/Green-Software-Foundation/meetup/milestone/3)
 Due by March 31, 2023. **Anna to drive this milestone.**
[M3 [April] Earth Week / Month](https://github.com/Green-Software-Foundation/meetup/milestone/4)
 Due by April 30, 2023  **Anna to drive this milestone.**

**Comment by tadanna** [comment]
I don't believe we need an issue to know what milestones we set! Up to the new PM if keep this or not - I have never used it as it was unnecessary admin for me.
