### ISSUE TITLE
2023 09 14 - GSF London - Code Green London event

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#126]
The GSF PM is responsible for updating this issue, ensuring the details section is up to date and the checklist marked based on the comments.

## Details

👥 Group: GSF London
👉 Title: Code Green London 
✍️ Organiser: Name | Affiliation | GitHub Handle
📆 Date: Date of the event
⏰ Time: From and To times (in local time)
📍 Venue: Where is the event going to be run?
 👥 Capacity: How many people can come?

## Checklist for Organiser

- [ ] Date/Time for the event has been decided
- [ ] Venue has been arranged
- [ ] topic/format decided
- [ ] speakers identified
- [ ] speaker bio/picture collected for Meetup.com & Social promotion
- [ ] Catering arranged for event (please note, GSF cannot provide funding)
- [ ] Event Sponsors in place if applicable

## PM Checklist: 
- [ ] Define event details: type, topic, audience (public, private, combo..)
- [ ] Date locked? **before publishing the event**
- [ ] Venue sourced? **before publishing the event**
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?

---

#### Meetup Page: 
- [ ] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover requested from @jenya-design
- [ ] Include venue in MeetUp event
- [ ] Publish Agenda
- [ ] @namrata-woke notified for upcoming newsletters

#### Design Requirements
Meetup Event Card - please drop a comment below to @jenya-design including the following details
- [ ] Location
- [ ] Date/Time
- [ ] Hosting Organisation
- [ ] Sponsor Logos
- [ ] Title of the Event
- [ ] Any other details.

Here is an example of an event card: 
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/92a4b076-81b9-4c42-896f-a484335fd7fb)

- [ ] If you require social assets, please add an additional comment.

#### Extra notes:
Please add this issue to the following Project Boards:
- [ ] **D: Graphic Design** if requesting assets
- [ ] **D: Marketing** for inclusion in Newsletters & GSF Social
- [ ] **Meetup** so it can be tracked as an event - _mandatory_

---

❇️ About Code Green London

Code Green London is an externally-organised group which is not professionally affiliated to the Green Software Foundation. We are sharing this event in the spirit of community, however, and we encourage everyone from the Green Software Community in London to participate.

🔔 [Please RSVP directly for this event on Eventbrite.](https://www.eventbrite.co.uk/e/green-coding-workshop-tickets-698352981567?aff=oddtdtcreator)

🗓️ Details of the Event

Join Code Green London for their first ever green code workshop! The idea for this session is to consolidate some green coding practices by using them to refactor and improve the source code of a not-so-sus webpage.

Whether you're a seasoned green tech professional, an entrepreneur looking to launch a new venture, or simply interested in learning more about the latest developments in sustainability and technology, Code Green London is the place to be.

T﻿his event will be a hands on workshop, so make sure to bring your laptop with you to be able to code along!

🧑🏽‍💻 The task:

We’ll be rewriting a React webpage to improve its sustainability. You’ll assess areas of improvement (either individually or in teams of your choosing), and then improve them using some green coding principles.
We want to keep the same core functionality, achieve excellent user experience, and minimise its CO2 emissions - outside of these requirements, you can do whatever you want!

We have a few resources available to help you including...

• Theodo UK’s Sustainability Calculator
A tool you can use to measure the emissions of your software, to assess whether your green coding actions are having the intended effect
• A Green Software Cheatsheet
Documentation of some of the green software principles, ideas and practices we use to help us in our pursuit of peak code sustainability.
• A team of developers on hand to help!

M﻿ake sure to bring your laptop as you will need it to participate!

🕚 The timings:

• 6:30 pm - 6:45 pm: Arrivals and drinks
• 6:45 pm - 7:00 pm: Introduction to the event and tasks
• 7:00 pm - 8:30 pm: Workshop (with a pizza break in the middle)
• 8:30 pm onwards: Wrap up and pub!

🍷 The sponsors

[Theodo](https://www.theodo.co.uk/)

Theodo was founded 14 years ago and comprises 700 employees across offices in London, Paris, New York, Casablanca and Cape Town. The company consists of agile full-stack software development and delivery experts, who partner with innovative companies looking to challenge their organisations and fast-growing companies looking to disrupt their market.
They have specialties across Web & Mobile, Serverless, Cloud Platforming, Data Engineering, DevOps, FinTech and HealthTech.

[Aleios](https://www.aleios.com/)

Aleios helps startups disrupt and enterprises remain competitive using the best of Cloud-Native, Serverless. We're experts in delivering highly scalable systems that connect people, liberate data, and, create innovation through technology.
Helping startups disrupt and large organisations remain competitive using the best of Cloud-Native. Building highly scalable systems we connect people, liberate data and create innovation through Serverless (the best of Cloud-Native).

[Mastercard](https://www.mastercard.co.uk/en-gb.html)

Mastercard, a global leader in the finance industry, empowers businesses worldwide with cutting-edge payment solutions. From seamless transactions to innovative financial services, they drive economic growth through technology.
By reshaping the digital economy, Mastercard empowers everyone — individuals, financial institutions, governments and businesses — to realise their ambitions.

😇 Everything else:

Code Green London is a meetup which aims to build the primary green tech community in London. You will have great networking opportunities with green tech innovators.
At Code Green London, we believe that green tech has the power to create a better future for all of us. Join us on September 14th, 2023, for an evening of learning, networking and collaboration towards building a more sustainable and equitable world.
If you have inquiries or would like to get in touch, send us a message on Meetup directly or contact Code Green London by email: codegreenlondon@theodo.co.uk

🔔 [Please RSVP directly for this event on Eventbrite.](https://www.eventbrite.co.uk/e/green-coding-workshop-tickets-698352981567?aff=oddtdtcreator)

**Comment by Jenya-design** [comment]
Hi @adamj89 please let me know my deadline 
You need only one Meetup Event Card, address and date are not set yet, right?
GSF logo should not be on the card, 3 sponsors only?

**Comment by adamj89** [comment]
Sorry @Jenya-design no graphic required for this!
