### ISSUE TITLE
Design Request: GSF Pro Network Banner

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#127]
Hi @Jenya-design 

On our Meetup Pro account (please view the page here: https://www.meetup.com/pro/gsf/) we have a banner image which currently uses some of the Environment Variables assets

You can see how this works from an admin perspective here

![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/25c33c00-7662-4e52-88a6-fadcd7fddf4e)

I was wondering if you could help us rethink this? I like the graphical element on the right with breathing space for the text on the left. Meetup seems to compress the image quite a bit so I'm looking for something that doesn't pixelate, dark colours but eyecatching.

**Comment by Jenya-design** [comment]
@adamj89 please check the update attached and [on GSF Drive](https://drive.google.com/drive/folders/1JVulw4CYIxTnMkh1kidI4OhSEbQeykN0?usp=sharing)
I was trying to keep the same composition, I think it works nicely as is
There are two version - with and without bg color. Size 1500x675 px

Please use 006D68 as the accent color for the page
Let  me know if you have any issues with the image
Thank you

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/06e971f5-2c77-4f65-bc7c-6338c948a2ff)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/b1f7e6b2-28ac-4194-a058-8411546ef234)

**Comment by adamj89** [comment]
Green graphic in use, closing this as it;s been used for a while :) thanks Jenya
