### ISSUE TITLE
2024-01-24 - GSF Brighton - AI Panel/Event

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#128]
The GSF PM is responsible for updating this issue, ensuring the details section is up to date and the checklist marked based on the comments.

## Details

👥 Group: Link to meetup group
👉 Title: Proposed title
✍️ Organiser: Name | Affiliation | GitHub Handle
📆 Date: Date of the event
⏰ Time: From and To times (in local time)
📍 Venue: Where is the event going to be run?
 👥 Capacity: How many people can come?

## Checklist for Organiser

- [ ] Date/Time for the event has been decided
- [ ] Venue has been arranged
- [ ] topic/format decided
- [ ] speakers identified
- [ ] speaker bio/picture collected for Meetup.com & Social promotion
- [ ] Catering arranged for event (please note, GSF cannot provide funding)
- [ ] Event Sponsors in place if applicable

## PM Checklist: 
- [ ] Define event details: type, topic, audience (public, private, combo..)
- [ ] Date locked? **before publishing the event**
- [ ] Venue sourced? **before publishing the event**
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?

---

#### Meetup Page: 
- [ ] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover requested from @jenya-design
- [ ] Include venue in MeetUp event
- [ ] Publish Agenda
- [ ] @namrata-woke notified for upcoming newsletters

#### Design Requirements
Meetup Event Card - please drop a comment below to @jenya-design including the following details
- [ ] Location
- [ ] Date/Time
- [ ] Hosting Organisation
- [ ] Sponsor Logos
- [ ] Title of the Event
- [ ] Any other details.

Here is an example of an event card: 
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/92a4b076-81b9-4c42-896f-a484335fd7fb)

- [ ] If you require social assets, please add an additional comment.

#### Extra notes:
Please add this issue to the following Project Boards:
- [ ] **D: Graphic Design** if requesting assets
- [ ] **D: Marketing** for inclusion in Newsletters & GSF Social
- [ ] **Meetup** so it can be tracked as an event - _mandatory_

**Comment by anewmandev** [comment]
Hello @Jenya-design - I am going to send logos over for the venue and sponsors for the event cover. Where would you like them sending?

**Comment by Jenya-design** [comment]
Hello @anewmandev could you please drop the link here? 
Google drive, Dropbox, wetransfer - whatever works best for you
Thank you

**Comment by anewmandev** [comment]
Hi @Jenya-design - thanks. Will send via a link. Do you need any particular dimensions?

**Comment by Jenya-design** [comment]
Thank you @anewmandev unless you need additional design assets for print we can work with what you have for the cover

**Comment by anewmandev** [comment]
Hello @Jenya-design. Have got all the sponsor logos and put them here. 

https://drive.google.com/drive/folders/1dBzmfqD2yM13xbrb8T9ufKt3vCO-cLWs?usp=sharing 

The Silicon Brighton ones I actually have a load of variations. The compressed folder was 60MB so I just grabbed a few PNG variations to keep the file DL size down but if needed I can send the .ai .svg or other file types - whatever you prefer?

**Comment by Jenya-design** [comment]
Thank you @anewmandev I think it's enough for web assets
Do you need the Meetup event card only? Do you need speakers cards (if yes, please provide the photos)?
Is this event a part of _Responsible AI GSF panel_ and should be aligned in term of design?
Please specify for me:
- Location
- Date/Time
- Hosting Organisation - is it GSF?
- Title of the Event

cc @adamj89

**Comment by anewmandev** [comment]
Hello @Jenya-design. 

This event is a roundtable discussion on AI but not officially part of the GSF Responsible AI Panel. As for design alignment I am not sure - over to @adamj89 to answer that one. 

I have created an event on meetup for this (with the GSF Brighton cover as a placeholder). I called it "The Environmental Impact Of AI". https://www.meetup.com/gsf-brighton/events/297235250/. 

- Location: [Wrap](https://wrap.space) 83 Queens Road, Brighton, BN1 3XE
- Date/Time: Weds 24th January 2024, 18:00
- Hosting organisations: GSF + Silicon Brighton + Wrap + Root & Branch (technically that is a mix of organisers, supporters and sponsors).  
- Title: "The Environmental Impact of AI"

Is that everything you need for now? 

Adam

**Comment by Jenya-design** [comment]
Yes. thank you @anewmandev

**Comment by adamj89** [comment]
@Jenya-design happy for you to align the design however you think best fits.

**Comment by Jenya-design** [comment]
@anewmandev @adamj89 please check the update for Meetup cover

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/45e1fa4b-6cfa-4548-9ef5-9c6adfa97d51)

**Comment by anewmandev** [comment]
Great stuff! Thanks very much - looks great!

**Comment by anewmandev** [comment]
@adamj89 @Jenya-design any chance I could get the .ai design file(s) for the above so I can create another event cover from it? This event maxed out very quickly (which is great) so I am running the same event two weeks later at a second venue.

**Comment by Jenya-design** [comment]
@anewmandev please copy [this canva](https://www.canva.com/design/DAFzq2rJUuY/ha7wtscF1Iru88fxplRu1A/edit?utm_content=DAFzq2rJUuY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) design before you adjust it, let me know if you have any problems with access

**Comment by anewmandev** [comment]
Fantastic, thanks @Jenya-design. I took a copy and edited. Want to check if happy or anything design wise needs a tinker? Adam

![Brighton-AI Panel2-Meetup_sponsors- 1200x676](https://github.com/Green-Software-Foundation/meetup/assets/69583564/989c4f85-29a4-45b0-80bd-bb7fa26ec661)

**Comment by Jenya-design** [comment]
Thank you @anewmandev I would recommend to keep left alignment for the text blocks on top. Also the space between the text and vertical green lines doesn't look even.  You can drop me the link and I'll adjust

**Comment by anewmandev** [comment]
Fantastic. Design eye! I've updated. 

![Brighton-AI Panel2-Meetup_sponsors- 1200x676](https://github.com/Green-Software-Foundation/meetup/assets/69583564/928f4a9e-0ac2-4b0d-a178-df3f0f999608)

I couldn't work out how to share the file with just you. Any idea how? Here is a public link for now if you do want to edit: https://www.canva.com/design/DAF2-EuyQKg/LnLuIf6HyoW6iiJ_3jDogw/edit?utm_content=DAF2-EuyQKg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Jenya-design** [comment]
Thank you @anewmandev 
I adjusted alignment a bit, please export and proceed
I think it's only public or share for a certain workspace in canva

**Comment by anewmandev** [comment]
Thanks @Jenya-design - much appreciated.

**Comment by anewmandev** [comment]
Hi @Jenya-design 

 I have the opportunity to promote our events locally (through [Silicon Brighton](https://siliconbrighton.com) who have various channels (emails, newsletters etc). They have requested dimensions 1,200 x 627 for landscape and 1,080 x 1,080.

In an effort to not ask for more of your time I have had a go on canva [here](https://www.canva.com/design/DAF3Zvkdcps/AoUzQkR9uzCEEpe4MDMmpw/edit) at doing the square version but I thought you might want to have a look and potentially change (or redo) this to your standards. 

You are allowed to laugh at my questionable design skills 😆 

Adam

**Comment by Jenya-design** [comment]
Thank you @anewmandev, please give me some time to adjust the composition. Is Thursday update ok?
Why would I laugh, I'll be just silently pleased that canva can't do all of my job automatically...yet :)

**Comment by anewmandev** [comment]
Hi @Jenya-design - absolutely - no major rush. Thanks for helping.

**Comment by Jenya-design** [comment]
@anewmandev please check the update in [your canva project](https://www.canva.com/design/DAF3Zvkdcps/AoUzQkR9uzCEEpe4MDMmpw/edit)
Let me know if you need any adjustments

**Comment by anewmandev** [comment]
Perfect. Thanks very much @Jenya-design - I hope to give you a break now! Have a great Christmas. Adam
