### ISSUE TITLE
2023-11-29 - Green Software - Northern Ireland - Launch Event 

### ISSUE THREAD

**Issue by Nevin243** [Green-Software-Foundation/meetup#131]
The GSF PM is responsible for updating this issue, ensuring the details section is up to date and the checklist marked based on the comments.

## Details

👥 Group: [Green Software - Northern Ireland](https://www.meetup.com/gsf-ni/)
👉 Title: Green Software Northern Ireland - Launch Event
✍️ Organiser: Marc Nevin | @Nevin243
📆 Date: 29/11/2023
⏰ Time: 18:00 - 20:00 GMT
📍 Venue: [Kainos Belfast](https://maps.app.goo.gl/AzRGANQqJAuD4kJe6)
 👥 Capacity: TBD - Capacity <50 (Not the target)

## Checklist for Organiser

- [x] Date/Time for the event has been decided
- [x] Venue has been arranged
- [x] topic/format decided
- [x] speakers identified
- [x] speaker bio/picture collected for Meetup.com & Social promotion
- [x] Catering arranged for event (please note, GSF cannot provide funding)
- [x] Event Sponsors in place if applicable

## PM Checklist: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [ ] Venue sourced? **before publishing the event**
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?

---

#### Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover requested from @jenya-design
- [x] Include venue in MeetUp event
- [x] Publish Agenda
- [x] @namrata-woke notified for upcoming newsletters

#### Design Requirements
Meetup Event Card - please drop a comment below to @jenya-design including the following details
- [x] Location
- [x] Date/Time
- [x] Hosting Organisation
- [x] Sponsor Logos
- [x] Title of the Event
- [ ] Any other details.

Here is an example of an event card: 
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/92a4b076-81b9-4c42-896f-a484335fd7fb)

- [ ] If you require social assets, please add an additional comment.

#### Extra notes:
Please add this issue to the following Project Boards:
- [ ] **D: Graphic Design** if requesting assets
- [ ] **D: Marketing** for inclusion in Newsletters & GSF Social
- [ ] **Meetup** so it can be tracked as an event - _mandatory_

**Comment by Nevin243** [comment]
Debating pushing this a week to give people time to sign up given the event isn't confirmed but...

@Jenya-design do you mind creating an Event Card for a meetup with this preliminary date?

 Location - [Kainos](https://www.google.com/maps/place/Kainos/@54.5869246,-5.9351463,15z/data=!4m6!3m5!1s0x486108f0520f2939:0xd4752e859722c88!8m2!3d54.5869246!4d-5.9351463!16s%2Fg%2F1tfkq54c?sa=X&ved=2ahUKEwidhqSv77SCAxVnUUEAHXySB8AQ_BJ6BAhZEAA&entry=tts) (4-7 Upper Cresant, Belfast)
 Date/Time - 29th Nov, 6pm - 8pm
 Hosting Organisation - Kainos
 Sponsor Logos - One Pending, Kainos at least, can get a logo if needed
 Title of the Event - Northern Ireland Launch Event
 
 Thanks!

**Comment by adamj89** [comment]
@Nevin243 sounds good, maybe nudge it by a week if you can't confirm by Wednesday (2 weeks before)?

Would recommend doing it no later than 6th/7th December otherwise you end up in silly season

**Comment by Nevin243** [comment]
@adamj89 If you're all happy enough with me creating the event I can do it tonight if you think it's far enough out..?

Confirming with the other speakers now for times, titles' and final sign-off

**Comment by Jenya-design** [comment]
Thank you @Nevin243 
Please attach sponsors logos here and I'll prepare the cover
Any available format will do

**Comment by Nevin243** [comment]
@Jenya-design 
![f8329ecb-d0f6-4384-8074-101d5cd927ce](https://github.com/Green-Software-Foundation/meetup/assets/22050696/85ad06ec-10d7-438f-bd78-466f724f8c3b)
![Kainos-alt-transparent](https://github.com/Green-Software-Foundation/meetup/assets/22050696/2041b656-9ec6-4c66-bb21-bf877851f190)
There's a png and an inverse, that work?

**Comment by Jenya-design** [comment]
@Nevin243 @adamj89 please check the update attached and let me know what you think

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/b0ded9a7-6948-45d3-a602-73aa6cf2ff4f)

**Comment by Nevin243** [comment]
Looks great @Jenya-design!

[Posted the event yesterday evening](https://www.meetup.com/gsf-ni/events/297380616/), got some people to share it so far 

Also, hey @NAMRATA-WOKE saw the note in the template RE the newsletter, 😄 are we able to share this event next one if it's not too late?

**Comment by Nevin243** [comment]
The event ran last night, thanks for all the support! Will look at drafting one for late January all being well, in the next week or two,

Want this issue closed now?

**Comment by adamj89** [comment]
Sounds like it was a good one! Congratulations :) 

Yes, happy to close this. Give me a shout when you're ready to plan the next one.
