### ISSUE TITLE
Custom Graphic for Green Software - Türkiye

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#133]
@Jenya-design, please could you work with @nexmind3 to get a meetup graphic created for **Green Software - Türkiye**

The graphic should include the word `Türkiye` in the main graphic. If @nexmind3 wants, we can include some regional landmarks in the graphic, though lets avoid flags/political symbols as per usual :) .

- https://github.com/Green-Software-Foundation/meetup/issues/132

**Comment by Jenya-design** [comment]
Hello @nexmind3, please let me know which landmarks you would like to include
Or you would like to go with general green software illustrations?
Thank you

**Comment by nexmind3** [comment]
Hi Jenya, Adam,

Of course. Here are some suggestions:

[Izmir Watch Tower](https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/db/d5/b2/saat-kulesi.jpg?w=1200&h=-1&s=1) _(The historical symbol of Izmir city)_

[Istanbul Bosphorus](https://www.oskartours.com/wp-content/uploads/2022/04/Bosphorus-Istanbul.jpg) _(with the combination of blue and green)_

[Cappadocia](https://www.voyelletour.com/ekstra/blog/denizli%E2%80%99den-kapadokya%E2%80%99ya-uzanan-gezi-furyasi.jpg) _(with fairy chimneys and air balloons)_

[Dead Sea Fethiye](https://minio.yuix.org/tto-rest/blog-content/oludeniz-2.webp)  _(with hillside rust)_

[Pamukkale](https://www.maloriesadventures.com/wp-content/uploads/2023/02/Pamukkale-turquoise-pools-natural-wonder-nature-main-image.jpeg) (cotton castles with travertenes)

[Nallıhan Bird Paradise](https://blog.biletbayi.com/wp-content/uploads/2020/02/nallihan-kus-cenneti-1.jpg) _(view of nature and birds)_

 [Salt Lake](https://roxcappadocia.com/assets/img/event/402505561641330777.jpg) _(drying up)_

**Comment by nexmind3** [comment]
Hi Jenya,
One more suggestion if i'm not late is: Gobeklitepe, Urfa
It is believed that the first Temple of the World which is believed to be a center of faith and pilgrimage during the Neolithic Period. The first and earliest three-dimensional depictions carved into stone are found here. According to scientists, the archaeological discovery of Göbeklitepe changed known human history.
[https%3A%2F%2Fwww.milliyet.com.tr%2Fmolatik%2Ftrend%2Fgobeklitepe-hakkinda-bilmeniz-gerekenler-87033](https://image.milimaj.com/i/milliyet/75/1100x570/617cfa8386b2440aec271b65.jpg)

**Comment by nexmind3** [comment]
The last suggestion is: Our founder's, Ataturk's monument.
[Anıtkabir](https://www.buseterim.com.tr/upload/default/2019/11/9/30agustostrkiye680.jpg)

That's all:)

**Comment by Jenya-design** [comment]
Hello @nexmind3 
Please check the update attached and let me know what you think
Sorry, I managed to incorporate only few of your suggestions, otherwise the composition would be too busy
Canva design[ here](https://www.canva.com/design/DAF2CiE05kA/GKJnLMEZeBNKLNOh1WUW1g/edit?utm_content=DAF2CiE05kA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

![Turkiye_Meetup_group cover_1200x676](https://github.com/Green-Software-Foundation/meetup/assets/69306070/e98859f4-fb60-4f26-9499-5836f3687433)

cc @adamj89

**Comment by nexmind3** [comment]
Hi Jenya, that's great, I liked the design very much. 

Thanks a lot.,

I have two points if it's ok for you

* In the name of Türkiye, we use İ instead of I, written with a dotted capital I. Is it possible for you to write it as TÜRKİYE?
* Could you please also study the standard design as you studied for other cities/countries if it is OK? 

Best regards

**Comment by Jenya-design** [comment]
Thank you @nexmind3
Please check the update attached, let me know if I misunderstood your 2nd request


![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/830128f1-5e02-4fab-9041-900fb0912b8c)


![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/62a20210-cc85-4d6e-a341-0cafedcb4998)

**Comment by nexmind3** [comment]
Hi Jenya

That's ok. Both seems very good. Thank you very much . We may use the first image in meetup group and during common posts as usual. 

But sometimes we would prefer second image for some social media posts or printed materials etc.

Best regards

Volkan / nexmind3

**Comment by Jenya-design** [comment]
Thank you @nexmind3 

Second image is a more standard design that was also used for Meetup group images for Berlin, Munich, Hamburg, Copenhagen, Milan, Stockholm, Paris, Madrid, London, Newcastle, Manchester and Barcelona. 

For printed materials please use ai or pdf vector files below 
https://drive.google.com/file/d/1Ldea4p1FVbEHg_t9ByXNNX2IuxiEyif0/view?usp=sharing
https://drive.google.com/file/d/1aLyzFOzVhH_1lc1S8sMAfPn7B_c-20L3/view?usp=sharing

Best regards
