### ISSUE TITLE
2024-01-11 - Green Software - Türkiye - Launch Event

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#134]
The GSF PM is responsible for updating this issue, ensuring the details section is up to date and the checklist marked based on the comments.

## Details

👥 Group: [Green Software - Türkiye](https://meetup.com/gsf-turkiye)
👉 Title: Green Software - Türkiye - Launch Event
✍️ Organiser: @Nexmind3
📆 Date: 2024-01-11 (11th January 2024)
⏰ Time: From and To times (in local time) to be defined by @Nexmind3
📍 Venue: Alsancak Mahallesi, The KAR İş Hanı, Atatürk Cd. No:132 Kat:7 Daire:71, 35220 Konak/İzmir, Türkiye
 👥 Capacity: 50

## Checklist for Organiser

- [x] Date/Time for the event has been decided
- [x] Venue has been arranged
- [x] topic/format decided
- [x] speakers identified
- [x] speaker bio/picture collected for Meetup.com & Social promotion
- [x] Catering arranged for event (please note, GSF cannot provide funding)
- [x] Event Sponsors in place if applicable

## PM Checklist: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

---

#### Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [ ] Event Cover requested from @jenya-design
- [x] Include venue in MeetUp event
- [x] Publish Agenda
- [ ] @namrata-woke notified for upcoming newsletters

#### Design Requirements
Meetup Event Card - please drop a comment below to @jenya-design including the following details
- [ ] Location
- [ ] Date/Time
- [ ] Hosting Organisation
- [ ] Sponsor Logos
- [ ] Title of the Event
- [ ] Any other details.

Here is an example of an event card: 
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/92a4b076-81b9-4c42-896f-a484335fd7fb)

- [ ] If you require social assets, please add an additional comment.

#### Extra notes:
Please add this issue to the following Project Boards:
- [ ] **D: Graphic Design** if requesting assets
- [ ] **D: Marketing** for inclusion in Newsletters & GSF Social
- [ ] **Meetup** so it can be tracked as an event - _mandatory_

**Comment by adamj89** [comment]
@nexmind3 Please could you provide the following information:

- Time of the event
- Who will be speaking (apart from you :))
- Can you provide a title for any talks
- Pictures/bio of speakers will be helpful

**Comment by adamj89** [comment]
@NAMRATA-WOKE this event is now live and is listed here: 
https://www.meetup.com/gsf-turkiye/events/298162790/

Please can we include this in all marketing channels this week and early next week?

**Comment by Jenya-design** [comment]
@adamj89 please check the update attached and [in canva](https://www.canva.com/design/DAF48SHKJXc/JFRs59uetPiZFP4CpSBLKw/edit?utm_content=DAF48SHKJXc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/0669101e-d325-4f06-b2fb-e8b6f1a93424)
