### ISSUE TITLE
2024-02-26 - GSF Oslo - February Meetup

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#139]
The GSF PM is responsible for updating this issue, ensuring the details section is up to date and the checklist marked based on the comments.

## Details

👥 Group: [GSF Oslo](https://www.meetup.com/gsf-oslo/events/298048644/)
👉 Title: Green Software Foundation Oslo - February Meetup [In-Person]

✍️ Organiser: @guidemetothemoon
📆 Date: 2024-02-26
⏰ Time: 4.30-6.30pm
📍 Venue: Microsoft Oslo
 👥 Capacity: How many people can come?

## Checklist for Organiser

- [x] Date/Time for the event has been decided
- [x] Venue has been arranged
- [x] topic/format decided
- [x] speakers identified
- [ ] speaker bio/picture collected for Meetup.com & Social promotion
- [x] Catering arranged for event (please note, GSF cannot provide funding)
- [x] Event Sponsors in place if applicable

## PM Checklist: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

---

#### Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [ ] Event Cover requested from @jenya-design
- [x] Include venue in MeetUp event
- [x] Publish Agenda
- [ ] @namrata-woke notified for upcoming newsletters

#### Design Requirements
Meetup Event Card - please drop a comment below to @jenya-design including the following details
- [ ] Location
- [ ] Date/Time
- [ ] Hosting Organisation
- [ ] Sponsor Logos
- [ ] Title of the Event
- [ ] Any other details.

Here is an example of an event card: 
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/92a4b076-81b9-4c42-896f-a484335fd7fb)

- [ ] If you require social assets, please add an additional comment.

#### Extra notes:
Please add this issue to the following Project Boards:
- [ ] **D: Graphic Design** if requesting assets
- [ ] **D: Marketing** for inclusion in Newsletters & GSF Social
- [ ] **Meetup** so it can be tracked as an event - _mandatory_

**Comment by adamj89** [comment]
@guidemetothemoon just to let you know @Jenya-design can create an event card for this for the event and also for Social media. It will look a bit like the sample card above. @Jenya-design , this is the current graphic for the event. 

![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/17e939d5-88c8-411b-ad88-c5003882d1db)

**Comment by Jenya-design** [comment]
Thank you @adamj89 @guidemetothemoon 

I'll create the cover using this info
📆 Date: 2024-02-26
⏰ Time: 4.30-6.30pm
📍 Venue: Microsoft Oslo

Do you need Microsoft logo and the exact address on the cover?

**Comment by guidemetothemoon** [comment]
Thanks for letting me know @adamj89 , I will ensure to request the designs for the future meetups as well.
@Jenya-design that sounds great, thanks! The name of the venue can be "Microsoft Norway". You can also add the venue address: Dronning Eufemias gate 71, Oslo.
We're still working out the food and drinks sponsor so we can skip adding the logo for now.

**Comment by Jenya-design** [comment]
@guidemetothemoon please check the update for the cover attached and let me know if you need any adjustments
There are 2 options with different logo combinations
Editable version here[ in Canva](https://www.canva.com/design/DAF6J9ExDFA/kqDNnIkkNWNJere5m0od2w/edit?utm_content=DAF6J9ExDFA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) in case you might need it, please make a copy before you apply any changes
Thank you!

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/5bcc5d67-4709-4e0c-b353-7415c198bd8c)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/bf2582d0-4b36-48ad-9c7d-114f48493edb)

**Comment by guidemetothemoon** [comment]
This looks great, thanks a lot @Jenya-design ! 😃
