### ISSUE TITLE
2024 02 26 - Code Green London / Climate Action Tech - February Meetup

### ISSUE THREAD

**Issue by April-Bates-Dev** [Green-Software-Foundation/meetup#142]
The GSF PM is responsible for updating this issue, ensuring the details section is up to date and the checklist marked based on the comments.

## Details

👥 Group: Code Green London / [Climate Action Tech](https://climateaction.tech/)
👉 Title: February Meetup
✍️ Organiser: @April-Bates-Dev
📆 Date: 26th February 2024
⏰ Time: 6:30pm - 9:00pm
📍 Venue: 2 Old Street Yard, London EC1Y 8AF, United Kingdom
 👥 Capacity: 80

## Checklist for Organiser

- [x] Date/Time for the event has been decided
- [x] Venue has been arranged
- [x] topic/format decided
- [x] speakers identified
- [ ] speaker bio/picture collected for Meetup.com & Social promotion
- [x] Catering arranged for event (please note, GSF cannot provide funding)
- [x] Event Sponsors in place if applicable

Link to eventbrite event : https://www.eventbrite.co.uk/e/code-green-london-climate-action-tech-meetup-tickets-820127331927?aff=oddtdtcreator

## PM Checklist: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

---

#### Meetup Page: 
- [ ] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover requested from @jenya-design
- [ ] Include venue in MeetUp event
- [ ] Publish Agenda
- [ ] @namrata-woke notified for upcoming newsletters

#### Design Requirements
Meetup Event Card - please drop a comment below to @jenya-design including the following details
- [ ] Location
- [ ] Date/Time
- [ ] Hosting Organisation
- [ ] Sponsor Logos
- [ ] Title of the Event
- [ ] Any other details.

Here is an example of an event card: 
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/92a4b076-81b9-4c42-896f-a484335fd7fb)

- [ ] If you require social assets, please add an additional comment.

#### Extra notes:
Please add this issue to the following Project Boards:
- [ ] **D: Graphic Design** if requesting assets
- [ ] **D: Marketing** for inclusion in Newsletters & GSF Social
- [ ] **Meetup** so it can be tracked as an event - _mandatory_

**Comment by Jenya-design** [comment]
Hi @April-Bates-Dev @Sophietn I can see all the details for the event cover are filled in. Shall I prepare the cover?

**Comment by Sophietn** [comment]
Yes please @Jenya-design, we'll be posting this one on our Meetup network asap. 
Attaching the Code Green London's image for additional context for you. 
Thank you
![Code Green London Meet Up_2](https://github.com/Green-Software-Foundation/meetup/assets/144015600/d4924eae-9936-4625-b393-decc01755cc0)

**Comment by Jenya-design** [comment]
@Sophietn @April-Bates-Dev please check the update attached and [editable canva file here](https://www.canva.com/design/DAF89PtJoHs/bBwKggPiYIbVz5g1Hs1AUQ/edit?utm_content=DAF89PtJoHs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
I was not sure which logos to add, so I made 3 versions. Let me know if you need any adjustments

![1](https://github.com/Green-Software-Foundation/meetup/assets/69306070/61361745-9791-4777-977b-ac4f1c1ef8f4)

![2](https://github.com/Green-Software-Foundation/meetup/assets/69306070/89f7c171-433d-4289-a82f-7730fbba616f)

![3](https://github.com/Green-Software-Foundation/meetup/assets/69306070/b4cb17e9-2819-41ae-8bed-32a40a97f2e0)

**Comment by Sophietn** [comment]
Thanks @Jenya-design these are great. I've used the top one.
[Event ](https://www.meetup.com/gsf-london/events/299294273/) is now published and announced to our meetup network.
