### ISSUE TITLE
Custom graphic for GSF - Netherlands

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/meetup#146]
@Jenya-design, please could you work with @WBurggraaf 
 To get a meetup graphic created for Green Software - Netherlands

The graphic should include the word The Netherlands in the main graphic. 
We can include some regional landmarks in the graphic, though lets avoid flags/political symbols as per usual :) 

Wilco, please suggest some landmarks Jenya could include in the meetup group visual. 

see this example for Turkiye https://github.com/Green-Software-Foundation/meetup/issues/133

**Comment by Sophietn** [comment]
https://github.com/Green-Software-Foundation/meetup/issues/145

**Comment by Sophietn** [comment]
Jenya - first event will be April 18th which needs promoting minimum 2 weeks prior

**Comment by JeroenRaij** [comment]
hi @Jenya-design  please work with me on this :) I think we need 2 designs, on for the community page itself and one for the 1th meetup on April 18th. See below the information that was requested. Please let me know if i missed anything.

**Cover Image for the community page:**
 
reffering to example https://www.meetup.com/gsf-hamburg/

name on the community page cover: the Netherlands (name for the community will be Green Software - the Netherlands)

**Cover Image for the meetup page:**

example :
![cover image example](https://github.com/Green-Software-Foundation/meetup/assets/163285663/5d2a7135-0574-4ada-ac0c-2aa296da4c5c)

details for cover:
Title: Community launch [live] event : Green Software the Netherlands
✍️ Organisers: HightTech Innovators & re:cinq
📆 Date: April 18th 2024
⏰ Time: 17:00 – 19:30
📍 Venue: HightTech Innovators, Rietveldenweg 40, 5222 AR ‘s-Hertogenbosch, Nederland

logos of HighTech Innovtors & re:cinq attached

![logo recinq](https://github.com/Green-Software-Foundation/meetup/assets/163285663/3386a842-3ae0-412a-8b91-6843d65038f3)


<img width="502" alt="HighTech Innovators horizontal white background option 2 PNG" src="https://github.com/Green-Software-Foundation/meetup/assets/163285663/d160cc39-ae7d-4a20-b8e1-4d67d36ea529">

@Sophietn @WBurggraaf

**Comment by Sophietn** [comment]
Thanks @JeroenRaij 

Do you have any requests for the Meetup group cover, to include landmarks from The Netherlands, rather than just the standard hills either side of the name? eg. [Brighton](https://www.meetup.com/gsf-brighton/), [Turkiye ](https://www.meetup.com/gsf-turkiye/)

**Comment by Jenya-design** [comment]
Thank you @JeroenRaij !
I'll send the update for April 18th cover asap
Could you also give me some example of the landmarks that are appropriate for the custom community image?

**Comment by JeroenRaij** [comment]
thanks @Jenya-design 

We could go for the typically windmill on the left, but then an 'old-school' version & a 'new school' version on the right to represen 'green'?

![homes](https://github.com/Green-Software-Foundation/meetup/assets/163285663/7a6e8d34-49d5-44aa-ad21-53b29d0cb9d7)
![1be18ef4-1](https://github.com/Green-Software-Foundation/meetup/assets/163285663/fa71d87b-f13b-4109-9287-7eb067c98934)

**Comment by JeroenRaij** [comment]
Hi @Jenya-design we want to launch the community page & the event page asap. When can we expect the 2 covers?

**Comment by Jenya-design** [comment]
@JeroenRaij @WBurggraaf @Sophietn  please review and let me know if you need any adjustments (same published issue #147 )

Launch event cover (can be reused for other events, editable canva file [here](https://www.canva.com/design/DAF_fzpkFqA/B4sP9_Q4KqZXrgAqX-GpZQ/edit?utm_content=DAF_fzpkFqA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
![Netherlands-Meetup_local-event- 1200x676](https://github.com/Green-Software-Foundation/meetup/assets/69306070/8ff70701-db14-4637-a28c-daaff1a85b46)

Custom group cover
![Netherlands_Meetup group-01](https://github.com/Green-Software-Foundation/meetup/assets/69306070/9ca3e923-a30f-456c-9d08-fdda1f66719b)

**Comment by Sophietn** [comment]
Closing this issue - we're discussing edits on https://github.com/Green-Software-Foundation/meetup/issues/147
