### ISSUE TITLE
Custom Graphic for GSF - Ireland

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/meetup#149]
@Jenya-design, please could you work with John Behan
To get a meetup graphic created for Green Software - Ireland

The graphic should include the word Ireland in the main graphic.
We can include some regional landmarks in the graphic, though lets avoid flags/political symbols as per usual :)

John, please suggest some landmarks Jenya could include in the meetup group visual.

see this example for Turkiye https://github.com/Green-Software-Foundation/meetup/issues/133

**Comment by Sophietn** [comment]
@jjmax75 please could you share some potential landmarks in Ireland that @Jenya-design could use for the Meetup group design? See other examples here [Brighton](https://www.meetup.com/gsf-brighton/), [Turkiye](https://www.meetup.com/gsf-turkiye/)

**Comment by jjmax75** [comment]
Thanks @Sophietn 

@Jenya-design some landmarks here include
Newgrange - https://heritageireland.ie/places-to-visit/bru-na-boinne-visitor-centre-newgrange-knowth-and-dowth/#gallery-2 or https://heritageireland.ie/places-to-visit/bru-na-boinne-visitor-centre-newgrange-knowth-and-dowth/#gallery-3
Round towers - https://en.wikipedia.org/wiki/Irish_round_tower#/media/File:Glendalough_Round_Tower.jpg
Old castles - https://en.wikipedia.org/wiki/Bunratty_Castle#/media/File:Bunrattybig.jpg
Dolmens - https://www.tuatha.ie/poulnabrone-dolmen/

All of these are ancient history but it's the common image portrayed of the country.

In keeping with the theme of Green Software - Ireland is the third highest in the world, per capita, producer of energy from Wind. https://en.wikipedia.org/wiki/Wind_power_in_Ireland Wind turbines are a common enough (sometimes controversial) feature of the landscape.

Also on the Green theme - Ireland is known as "the emerald isle", forty shades of green, etc... - this is down to the large rural area of the country and damp climate that keeps the place well watered 😆 

The people are often cited as a feature of the country - poets, musicians, writers, etc.... If you'd like to include someone from that side of things let me know.

**Comment by Jenya-design** [comment]
Thank you @jjmax75 !

**Comment by Sophietn** [comment]
Hi @Jenya-design please could you share an estimated date when you'll have the Ireland meetup group cover ready? Thanks :)

**Comment by Jenya-design** [comment]
@Sophietn if it's ok, I'll share the update for both covers on Monday

**Comment by Jenya-design** [comment]
@jjmax75 @Sophietn please check the group cover and let me know if you need any changes
Thank you

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/de7bbeab-d5ae-40ea-bea9-044288aaf1f7)

**Comment by jjmax75** [comment]
Thanks @Jenya-design this looks great

**Comment by Sophietn** [comment]
Thanks both! 
I'll create the new meetup group on the platform today @jjmax75
