### ISSUE TITLE
Earth Week - encourage local hosts to create events

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#15]
Suggested by ML / Meetup, to be discussed:

- Create 1-3 event templates via the Templates tab of the Pro Dashboard 
- Encourage local organizers to plan local events for their group during the day
- Event templates could cover a few ideas of event formats such as panel discussion, workshop with a guest speaker or even a roundtable discussion
- You can easily message the local organizers via the Members tab by using the filter ‘Role’

**Comment by tadanna** [comment]
Comments from the weekly call on February 6th: 
for Earth Week give an event proposal to the organisers and invite them to organise an event within their group. 
For example: we organise a network event for the week, with info material and link back to the course. We can let the organisers know and propose them a framework idea around which they could organise an event on the same week. Maybe a self-learning event? 

_It could be something that inspires them in case they are struggling in finding ideas, but they could organise something completely different if they want to._

**Comment by adamj89** [comment]
Closing this but will keep idea on hold for future moments in time.
