### ISSUE TITLE
Ideas & Inspirations

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#26]
Collection of ideas and inspirations to review and implement within the Meetup community at any point in time.

**Comment by holanita** [comment]
Event types suggested by Asim in our weekly call: show and tells, watch parties

**Comment by tadanna** [comment]
- add upcoming events to the external GS newsletter
- Can we add a link to the meetup on the GSF page? At the bottom, close to LI and Twitter logos
- Include a direct link to MeetUp under the Community WG page

fyi @jawache
