### ISSUE TITLE
World Environment Day June - Promotion

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#28]
- [ ] LinkedIn
- [ ] GSF Website
- [ ] Meetup events (events within the groups)
- [ ] Facebook: IT/developers related groups?
- [ ] Meetup team promotion (contact ML end of April to pick up the conversation)

**Comment by tadanna** [comment]
This issue started with an opportunity we have from Meetup to promote our events through their platforms. The idea to have some events organised for Earth Week in April, but the WG decided to move this effort to June 5th for the World Environment day. 

What Meetup was offering us FOR FREE:

> - Two main options you can choose from: 1) post on Instagram or 2) post(s) on Twitter 
> - Either way, we'd need to have your choice with relevant assets at the latest 3 weeks before
> - If you choose Instagram...: Meetup has 91K followers; 1 post only; Feature one group within the GSF network or the entire network; CTA will be focused on joining that one group and/or the global network; We'd need high quality pictures of past events hosted within the GSF community, and ideally a quote from the GSF, a group leader or a member showcasing why this community is special
> - If you choose Twitter...: Meetup has 68K followers, more tech-focused than Instagram; We could do a series of Tweets ; CTA will be focused on joining a specific event 
> - I'm resharing the ideas we discussed together: 1) info-session about the certification, 2) working session to get people to complete the certification or 3) local events hosted by organizers

Meetup would do this for us only it falls on a bigger picture for them (such a national celebration of something!), otherwise we would have to pay for this. We should not miss this opportunity!

**Comment by tmcclell** [comment]
Anne - Podcast event? Around the same time of State of GSF report - Namrata. Adam - livestream the podcast? Anne - Intro being released soon so may be able to sync with that. Adam to move forward with a subgroup (Anne, Tammy)
