### ISSUE TITLE
Plan Q1 Meetup Test Events

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#29]
Define the exact test events for Q1 and get started. (at least 5)
The purpose of these events is for the organisers to self-organise and create events that are scalable in other Meetup groups with very little help/involvement from the GSF team. 

**Meetup organisers need to become comfortable running their own Meetup events.**

**Comment by holanita** [comment]
Timelines as discussed:

Q1 test events:
- work with volunteers on test events by March 6
- _**Anna OOO March 6-13**_
- share feedback via email or in a group meeting by March 31

Q2 Earth Week preparation:
- MEETUP talk to Meetup about GSDay by February 10
- have the **GSDay network event** set up on Meetup.com by March 1
- have **local events** set up on Meetup.com by March 17
- MEETUP Provide to the marketing team relevant assets (at least link to the event pages) **TBD**
- MEETUP Marketing team to prepare creative TBD
- MEETUP GSF to Review creative TBD
- MEETUP Marketing to execute on the creative (e.g. publish blog or social media, etc.) TBD
- GSDay in the week of April 16th-22nd

**Comment by tadanna** [comment]
Closing the issue as we are tracking the events separately
