### ISSUE TITLE
Meetup - email list to communicate with volunteers

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#32]
Current status:
- We currently have one email list (meetup@) which we use internally and to manage our meeting account.
- Volunteers should NOT have access to this.

Ideas:
- We could create another one (maybe events@ or eventhosts@) for announcements which are relevant for all volunteers.
- TBD if volunteers should be allowed to send random emails to the email group (maybe allow but moderate)
- Local asks and needs will have to be discussed one-by-one with each volunteer.
- At the end of every Q we could send an email to all organisers, directing them to our event templates, latest discussions within GSF, possible event topics (?) ..to keep them engaged, help them brainstorming on next events etc.. By Anna: it could be a short "organiser toolkit", that links back to all our resources, including our extended guidelines
- we could include a list of the last 3 events that have taken place and the next 3 planned

**Comment by tadanna** [comment]
Ideas to include in a monthly newsletter: 

- released podcast episodes (might give ideas for topics)
- GS talks during the past month
- Planned events
- GS events and milestones that could be leveraged for organising events 
- Reminders of WG calls

fyi @jawache

**Comment by tadanna** [comment]
I have sent out a first email to the email group, and will send out a second one on Friday March 31st. 
to do here: 

- [ ] define a strategy. It would be great to have a recurring email to send out (once or twice a month) that includes (some of) the above topics to keep the organisers engaged
- [ ] Make sure to add the new organisers to the list every time

This task can be deleted once the action items are included in the process.
