### ISSUE TITLE
Meetup - figure out the right setup for our network

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#33]
Draft 
TBD next Monday in the weekly review call.
Working on a set of questions that should be discussed with the Meetup team. 
https://docs.google.com/document/d/1t2_nCa8FJW4YxBzu_U3t35PtKyik2VdJxlGrTnKwzsI/edit

**Comment by holanita** [comment]
TBD next Monday with Asim whether we want our network to look like [hyperledger](https://meetup.com/pro/hyperledger) or [azure](https://www.meetup.com/pro/azuretechgroups/). Also to be discussed: 
- branding, 
- use of our logo, 
- disclaimer about how we are related to the events/groups, 
- who should be the organizer, [branding and use of decks](https://drive.google.com/drive/u/0/folders/11Ty2C4l4gVUMES9cLw0glrhD4EbvHDif) etc.

**Comment by jawache** [comment]
> See attached what it means to have a branded network page
> [Branding Opportunities with Meetup Pro.pdf](https://github.com/Green-Software-Foundation/meetup/files/10557289/Branding.Opportunities.with.Meetup.Pro.pdf)
> 

Just so we are on the same page this is our account level right? We have a branded account and can get all those features right?

Or is a branded account different to a meetup pro account?

**Comment by tadanna** [comment]
Closing this issue as it overlaps with: https://github.com/Green-Software-Foundation/meetup/issues/36
