### ISSUE TITLE
Manage volunteer database

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#34]
From now on we should be storing all the details af the volunteers [in this spreadsheet](https://docs.google.com/spreadsheets/d/165Nu3mCrzYpIi2ua34TmSTdOWdFIkukN-oXyd3Fq9ZQ/edit#gid=0). The original table was removed from the guidelines. @tadanna please review, update and add data as you see fit. You can maintain this database based on the conversations you are having with the volunteers. If you have any questions, just add a comment or tag me in the file or reach out here.

**Comment by tadanna** [comment]
Handover update: Asim had some thoughts on how to recruit more volunteers moving forward but we never discussed this. Take back the conversations and define a strategy.
