### ISSUE TITLE
Weekly Meetup Planning #2

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#35]
This is a checklist for the week between Jan 30 and Feb 3 based on the meeting held on January 30.

Action steps for this week:
- https://github.com/Green-Software-Foundation/meetup/issues/8 especially the guidelines!
- https://github.com/Green-Software-Foundation/meetup/issues/34
- https://github.com/Green-Software-Foundation/meetup/issues/5 share the guidelines and discuss next steps 
- https://github.com/Green-Software-Foundation/meetup/issues/29

Meetup discussions:
- https://github.com/Green-Software-Foundation/meetup/issues/33 
- https://github.com/Green-Software-Foundation/meetup/issues/17 

Keep in mind:
- https://github.com/Green-Software-Foundation/meetup/issues/21

To be discussed with the Meetup team in a call in February:
@holanita to loop in @tadanna and organize the call
- https://github.com/Green-Software-Foundation/meetup/issues/13 (new cover images, etc.)
- https://github.com/Green-Software-Foundation/meetup/issues/14 (the moment in time)
- https://github.com/Green-Software-Foundation/meetup/issues/15 (provide them with event templates)
- https://github.com/Green-Software-Foundation/meetup/issues/16
- https://github.com/Green-Software-Foundation/meetup/issues/17

**Comment by holanita** [comment]
_Note: discuss with Asim branding and hyperledger vs azure. This text is to be reviewed and added back to the guidelines:_

The official GSF meetup groups run by GSF staff all use GSF branding, however, there is some flexibility as to the design of your group page. When posting images and captions for your meetup, consider using official GSF logos. When promoting event speakers and attendees, local city and event spaces as well as when including captions, make sure that the information is concise and considerate. Productive posts combine engaging photos with captions that are lively and powerful without resorting to sensationalism. Please find all the relevant assets [here](https://docs.google.com/document/d/1ZiEjvcHUc8w7f2UPFqcDX-2IZOxa90JDiScEw-S8SBo/edit#heading=h.gy016egwjo6n). If you have any questions please contact us at meetup@greensoftware.foundation.

**Comment by tadanna** [comment]
@holanita not sure where to keep an agenda/points to discuss in the next meetings. I drop here a couple of things, but let me know if I should simply add these into the Google Meet notes: 

- how to create a new group
- how to make someone an assistant organiser

**Comment by holanita** [comment]
here is the right place, we'll roll forward all the pending topics to the next agenda when we create it

**Comment by holanita** [comment]
ideally, we should create the next agenda on Fridays. do you want to start doing it yourself?

**Comment by tadanna** [comment]
@holanita closing this issue - I have carried the open tasks/questions in #37
