### ISSUE TITLE
London MeetUp - Q1

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#41]
_Use the issue's comments to track updates, reminders and communications. Remove/Add sections where needed._

_______________

> _EVENT DETAILS_

**MEETUP GROUP**: [Green Software - London](https://www.meetup.com/gsf-london/)
:point_right: **EVENT**: Event title

:link: Event page URL

:calendar: Date/Time: March 23rd

:busts_in_silhouette: Capacity: 

:round_pushpin: Location: MasterCard office at CanonLane

:writing_hand: Organisers: Sarah Hsu, Daniel Vaughan, Michala Eva, Liya Mathew

_______________

> _EVENT PREP_

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover
- [x] Include venue in MeetUp event
- [x] Publish Agenda

Extra notes:

**Comment by tadanna** [comment]
@greenhsu123 FYI you and Daniel are Assistant Organisers on the MeetUp Group. Let me know if I should add anybody else from the people organising or if this would be enough. :)

**Comment by LiyaMath** [comment]
Attention London-based green software enthusiasts! Our inaugural Green Software Foundation London meetup is coming up, and it’s packed with an incredible line-up of activities that you won’t want to miss. We’ll have an insightful talk on the underlying Principles and Patterns of green software, a panel discussion featuring some of the best and brightest minds in green software, and plenty of networking opportunities. So, don’t miss out on this opportunity to learn, connect, and engage; mark your calendars and get ready for an exciting evening of insights, discussions, and connections; we can’t wait to see you all!
**Venue:**
Mastercard, 1 Angel Lane London EC4R 3AB
**Agenda:**
**Date:** Thursday 23rd of March, 2023
**Time:** 6:00 pm to 9:00 pm
•	**6:00 pm:** Welcome- Doors open.
•	**6.30 pm:** Introduction Green Software Foundation(GSF) and Mastercard.
•	**6:45 pm:** Principles an Patterns of green Software- what you need to know for building green software and  how these principles can be put into practice.
o	_Liya Mathew, SRE Analyst, Goldman Sachs & Sarah Hsu, SRE VP, Goldman Sachs, Green Software Training Project Chair, Green Software Foundation._ 
•	**7:15 pm:** Q&A/ Panel discussion:
o	_Chris Adams, Executive Director, Green Web Foundation.
o	Asim Hussain , Executive Director & Chairperson, Green Software Foundation.
o	Daniel Vaughan, Manager, Product Architecture, MasterCard.
o	Sarah Hsu, SRE VP, Goldman Sachs, Green Software Training Project Chair, Green Software Foundation.
o	Liya Mathew, SRE Analyst, Goldman Sachs._
•	Closing, networking & drinks.
