### ISSUE TITLE
Create a meetup group cover for Sao Paulo

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#43]
Hey @Jenya-design we have a new group on Meetup and we need a group cover image. Do you have a Canva template that you could share with us or will you do this yourself? Please keep @tadanna in the loop as she is in charge of meetup now. 

PS: I believe we have to use the dark green theme for Sao Paulo as it's the same timezone as the US.

**Comment by Jenya-design** [comment]
Hello @holanita 
Please check the cover [here](https://drive.google.com/file/d/1xlyhmreF4SwrNTDZUSt_eDI5Iymdt81K/view?usp=share_link) (the source file is in Ai) 
It's in the [same folder](https://drive.google.com/drive/folders/1TlOZof1Z_oqUiblb6mYzR3qeJr8in_3f?usp=share_link) as other covers
Let me know if you prefer to have it as a Canva template

Sean mentioned that I should track my tasks in a different way now, marking the projects
He mentioned the tags that you'll add. Could you show me where to check them?

Thank you

cc @tadanna

**Comment by tadanna** [comment]
@Jenya-design thanks for the cover! If you do then in Ai, no worries about Canva - I will just ask you whenever it's needed :)

As for the tags - are you maybe talking about Toggl? Not sure if it's the same for you, but he told me to track the time in Toggl and to use the tags that he created within the tool.
