### ISSUE TITLE
Gurgaon Event - Q2 5-May-2023

### ISSUE THREAD

**Issue by akshitbatra** [Green-Software-Foundation/meetup#48]
PM is responsible for updating this issue, ensuring the details section is upto date and the checklist marked based on the comments and mak

## Details

👥 Group: [GSF Gurgaon](https://www.meetup.com/gsf-gurgaon/)
👉 Title: Sustainable CX (Customer Experience)
✍️ Organiser contact: Akshit Batra | Thoughtworks | @akshitbatra 
📆 Date: May 5th
Time: 10 AM IST
📍 Venue: Thoughtworks Technologies India
 Capacity: How many people can come?

 

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover
- [x] Include venue in MeetUp event
- [x] Publish Agenda

Extra notes:
Meetup link: [Green Software Foundation Gurgaon Meetup May'23](https://www.meetup.com/gsf-gurgaon/events/292979829/)

**Comment by tadanna** [comment]
@akshitbatra well done on this issue! Few comments to move forward:

- do you have a time?
- you said this event will be open, do you mean open to the public and not only for employees?
- can you please elaborate further on the topic? As far as it's related to GS topics it will be fine, but I believe there needs to be an indication on what will be discussed.
- Do you have an agenda?
- Do you have speakers?

Asking all this as the event is less than 2 weeks ahead which means we should already post it on meetup. You can create the event yourself, but we will need to know the above details (also to create the cover design).

Let me know!

**Comment by tadanna** [comment]
@akshitbatra do you have any update on this? I know you were looking into new dates either in April or May..anything pinned down yet? 

fyi @Oleg-Zhymolokhov

**Comment by tadanna** [comment]
Wonderful @akshitbatra ! Please keep @Oleg-Zhymolokhov up to date on this issue - he will follow the meetup program starting from next week (I stop working with GSF this week).

**Comment by Oleg-Zhymolokhov** [comment]
Hello @akshitbatra, have you created the event on the Meetup platform for this? You can specify all this data there.

**Comment by akshitbatra** [comment]
Hello @Oleg-Zhymolokhov,
Regarding Brand assets for the event, do we need to use GSF branded event cover and Slide deck?

Also, whom we can contact to get the above mentioned details created like cover and social media posters and slide deck for Meetup ?

**Comment by Oleg-Zhymolokhov** [comment]
@Jenya-design do you have these items pre-created for the existing cities?

**Comment by Jenya-design** [comment]
Hello @Oleg-Zhymolokhov @akshitbatra 

We have multiple templates, you can preview them via the links below
Let me know if you need my help with any of those or access to edit canva templates

1. GSF basic slide deck template (you need to export the theme, so you can create the slides with GSF fonts and colors right away)
https://docs.google.com/presentation/d/1EPrBI25DrGRluABRraM92mI56zcb2I32cgchxLBIXbM/edit?usp=share_link

2. [Icons](https://drive.google.com/drive/folders/1cYj_0gSKfCKNpnXvbFO-5umTHIjW8lcG?usp=share_link) and [illustrations](https://drive.google.com/drive/folders/1z48YW1JNvhRx68CmM7CMC1h-1MxQkfjG?usp=share_link) you can use for the deck and canva

3. Meetup cover template
https://www.canva.com/design/DAFd8BweuWs/vtUhIRsxMdAtBrqNP51sIA/view?utm_content=DAFd8BweuWs&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

4. Social media posts templates
https://www.canva.com/design/DAFd8vPBnDI/2Bs1IFMxNdThdiBz5DEdLw/view?utm_content=DAFd8vPBnDI&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

https://www.canva.com/design/DAFdR3buaRM/IpOnGgQ6LWEpM0lGtQED-A/view?utm_content=DAFdR3buaRM&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

5. Meetup events and speakers templates (there are multiple templates depending on the numbers of sponsors, speakers etc)
https://www.canva.com/design/DAFd8CdF8FU/vfsOxyewMqs9tnUc2-UUqg/view?utm_content=DAFd8CdF8FU&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

https://www.canva.com/design/DAFd8eouZY0/2kkRq2tPd7Y_-1Dq9RktPQ/view?utm_content=DAFd8eouZY0&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

https://www.canva.com/design/DAFd8GYy0pQ/PHyxbz4MfgxK7w8jjnuCxw/view?utm_content=DAFd8GYy0pQ&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

https://www.canva.com/design/DAFcFeVfc2Q/bjBeTzcwjuljSIW6Jy_NXw/view?utm_content=DAFcFeVfc2Q&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

https://www.canva.com/design/DAFd8GB2Iok/8IjV3XjYy7hcnDyiPIJgbg/view?utm_content=DAFd8GB2Iok&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

**Comment by akshitbatra** [comment]
Hello @Jenya-design, 
Could you share canva edit/copy access for these designs :

1. https://www.canva.com/design/DAFd8eouZY0/2kkRq2tPd7Y_-1Dq9RktPQ/view?utm_content=DAFd8eouZY0&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu#5
2. https://www.canva.com/design/DAFd8GB2Iok/8IjV3XjYy7hcnDyiPIJgbg/view?utm_content=DAFd8GB2Iok&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu
3. https://www.canva.com/design/DAFd8CdF8FU/vfsOxyewMqs9tnUc2-UUqg/view?utm_content=DAFd8CdF8FU&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu#3
4. https://www.canva.com/design/DAFdR3buaRM/IpOnGgQ6LWEpM0lGtQED-A/view?utm_content=DAFdR3buaRM&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu#4

Email id: akbatra567@gmail.com 

P.S: Will remove email id once, you give me access.

**Comment by Jenya-design** [comment]
@akshitbatra please check your email, you should now have the invitation to edit those templates
Please don't forget to make a copy of the file before you start adjusting it for your event
Thank you!

**Comment by akshitbatra** [comment]
thank you @Oleg-Zhymolokhov

**Comment by akshitbatra** [comment]
@Oleg-Zhymolokhov 

Updates:
Meetup event URL: https://www.meetup.com/gsf-gurgaon/events/292979829/

**Comment by Oleg-Zhymolokhov** [comment]
@akshitbatra please meet Adam (@adamj89). He's the new Community PM and will be taking over the Meetup project from me.

**Comment by akshitbatra** [comment]
Hello @adamj89, 
The Event was successfully executed.
As for the next steps wanted to check, do we upload the recordings on GSF Youtube channel like we did for Summit last year ? 

cc: @jawache

**Comment by adamj89** [comment]
Hi @akshitbatra - yes please if you could upload directly or provide the recording to me then that would be amazing.

Glad to hear the event went well. What was the turnout? Do you have plans for further events yet? 

Adam

**Comment by adamj89** [comment]
@akshitbatra hey. hope you're doing well. Do you have any updates on the recording and/or future event plans? Thank you. AJ

**Comment by akshitbatra** [comment]
> @akshitbatra hey. hope you're doing well. Do you have any updates on the recording and/or future event plans? Thank you. AJ

@adamj89, for the recording what should be preferred ? 
1. One video with the whole event ?
2. Talks cut separately ? - multiple videos

For now, there is no plan for any future event plans, At least for Gurgaon location. Will update whenever we start planning again.
