### ISSUE TITLE
Tokyo - April 21

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#49]
PM is responsible for updating this issue, ensuring the details section is upto date and the checllist makred basd on the comments and mak

## Details

👥 Group: [Link to meetup group](https://www.meetup.com/gsf-tokyo/)
👉 Title: GSF MeetUp Tokyo
✍️ Organiser: Toru Shimogaki | NTT, Daiyu Hatakeyama | MSFT
📆 Date: 21st April
Time: 19:00 - 21:00 (JST: GMT+9)
📍 Venue: Shinagawa Grand Central Tower 31F, Konan 2-16-3, Minato-ku, Tokyo | https://www.microsoft.com/ja-jp/mscorp/branch/sgt.aspx
 Capacity: 30 (pubic event)

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover
- [x] Include venue in MeetUp event
- [x] Publish Agenda

Extra notes:

**Comment by YaSuenag** [comment]
Hi @tadanna ! I'm Yasumasa from NTT DATA. I'm working with Toru, so I share further information about this event in Japan. Could you update the description of this issue?

👉 Title: GSF MeetUp Tokyo
✍️ Organiser: Toru Shimogaki | NTT, Daiyu Hatakeyama | MSFT
📆 Date: 19, April
Time: 19:00 - 21:00 (JST: GMT+9)
📍 Venue: Shinagawa Grand Central Tower 31F, Konan 2-16-3, Minato-ku, Tokyo
Capacity: 30

**Comment by tadanna** [comment]
Hi @YaSuenag thanks for the updates, I have made the changes! Can you please let me know: 

- is the event open to the public or only for employees?
- is there any speaker sourced? 
- do you already have an agenda to share?

I would recommend to publish the event on MeetUp two weeks before and not latest than April 10th. 
We can either prepare a cover with the speakers (especially if they are external) or without, please see below examples and let me know what you think. 

<img width="857" alt="Screenshot 2023-03-23 at 11 19 08" src="https://user-images.githubusercontent.com/122878451/227173435-a4580d23-2479-4b75-8c58-c75bde2c5ec9.png">
<img width="1431" alt="Screenshot 2023-03-23 at 11 17 34" src="https://user-images.githubusercontent.com/122878451/227173447-93e0d0ec-6394-45e4-9a85-3494981ba52f.png">

**Comment by YaSuenag** [comment]
> is the event open to the public or only for employees?

We are preparing as a public event. The others are under construction...

I give further information ASAP.

**Comment by YaSuenag** [comment]
@tadanna Can you update this event in below?

* Date: 21th April

And also I'm happy if you add venue URL: https://www.microsoft.com/ja-jp/mscorp/branch/sgt.aspx

**Comment by tadanna** [comment]
@YaSuenag details updated! 
please tag @Oleg-Zhymolokhov in this issue to share updates on the organisation of the event, and keep in mind that it would be best to publish it on meetup about 2 weeks prior to the date.

**Comment by YaSuenag** [comment]
@tadanna @Oleg-Zhymolokhov 

Thank you for updating event details. Could you update the subject of this issue? It is still April 19.

> keep in mind that it would be best to publish it on meetup about 2 weeks prior to the date.

Sure, we are preparing to publish some stuffs for this event.

**Comment by YaSuenag** [comment]
@tadanna @Oleg-Zhymolokhov

Could you update the subject of this issue? It is still April 19.

**Comment by shinmatsu** [comment]
Hello @tadanna and @Oleg-Zhymolokhov . I'm Shin from NTT DATA. Let me post the updates.
Title: GSF MeetUp Tokyo
Organiser: Toru Shimogaki | NTT, Daiyu Hatakeyama | MSFT
Date: 21st April
Time: 19:00 - 21:00 (JST: GMT+9)
Event: Public event held both online and offline
Venue: Shinagawa Grand Central Tower 31F, Konan 2-16-3, Minato-ku, Tokyo | https://www.microsoft.com/ja-jp/mscorp/branch/sgt.aspx
Venue Capacity: 30 

The event and its agenda have already been published in Meetup. (only in Japanese)
https://www.meetup.com/ja-JP/gsf-tokyo/events/292676506/

Speaker: Toru Shimogaki(NTT DATA), Yasumasa Suenaga(NTT DATA), Daiyu Hatakeyama(Microsoft Japan), Masataka Takagi(Intel)

**Comment by Oleg-Zhymolokhov** [comment]
Hi @shinmatsu. Can you edit the event on the Meetup website so that the speakers are visible?

**Comment by shinmatsu** [comment]
Thank you, @Oleg-Zhymolokhov . 
Could we have a cover image for this event which we can find in #53 . We prefer it in ppt form.
In that thread, the link to Canva is attached. But I don't have a right to access it.

**Comment by adamj89** [comment]
@YaSuenag @shinmatsu Hi - I hope you are both well. I am the new Community/Meetup PM for Green Software Foundation. It would be good to hear how the event went and whether you have plans for some further meetups in the future.

**Comment by shinmatsu** [comment]
Hi @adamj89 
There were roughly 30 attendees at the meetup, and it had a great atmosphere. We will think about the next, but don't have a concrete plan as for now.

**Comment by shinmatsu** [comment]
Hi @adamj89 
There were roughly 30 attendees at the meetup, and it had a great atmosphere. We will think about the next, but don't have a concrete plan as for now.

**Comment by adamj89** [comment]
Thank you! I am closing this issue now, please feel free to contact me when you have plans.
