### ISSUE TITLE
Contact volunteers

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#5]
Last year Asim & Doha used [this google form](https://docs.google.com/forms/d/e/1FAIpQLSd8NpRJWexDJt9Qv4P8zK6uKteun6d7Q1w6eUUT_ClQv92RQA/viewform) to recruit hosts. Responses can be viewed [here](https://docs.google.com/spreadsheets/d/1FzLtXV-HgojQNy5vz0pZKdBBkScYNPaOeE0XCMXNHP8/edit?resourcekey#gid=1895973938) (access restricted to ops team). Those who volunteered are listed in the final guidelines [here](https://docs.google.com/document/d/1ZiEjvcHUc8w7f2UPFqcDX-2IZOxa90JDiScEw-S8SBo/edit#bookmark=id.ugycz5p4y6pa).

Next steps could be to:
- reach out to volunteers and confirm if they are still available and interested
- share our plans with them so they can figure out how they could contribute
- once done, we should create a volunteer package that makes it easier for them to get started (e.g. FAQs), etc etc,

FOR THE FUTURE (after Q1 event tests): 
Recruit more volunteers. To support existing groups and to create new ones. 
What needs to be defined:

- some folks (non-members) sent us a message via meetup expressing their interest to collaborate or run their own groups. contact them
- what would be their tasks
- what would the GSF event manager do
- how many people do we need
- what platforms do we use to recrute (newsletter, community wg email list..)

**Comment by tadanna** [comment]
@holanita I believe we can close this issue for now? 
Related following tasks can be found here: 
#31 
#34
