### ISSUE TITLE
Organise feedback call with meetup organisers

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#50]
Organiser a call with the meetup organisers in the meetup-organisers group to discuss:

- learnings from Q1
- difficulties and challenges in organising events
- what support do they need from the PM?
- things that went well in the organisation
- what tools would they prefer to keep track of the event planning and communication with the PM?
- next things coming up with GSF

**Comment by adamj89** [comment]
@jawache any suggestions on the best way to communicate this?
