### ISSUE TITLE
Create Image for Meetup Tokyo

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/meetup#53]
What: GSF Tokyo is hosting a Meetup, Wednesday, April 19, 2023 at 7:00 PM - 9:00 PM JST 
Why: Want to promote on social and in the newsletter 

The image should look similar to the one created for [Meetup London](https://drive.google.com/drive/folders/1iy5UVug4vL1-REehfLEURkVuQWsdAZla) but do not need to include virtual option. It's only in-person.

Instead of "hosted by" can we instead replace that section with talks from Intel, Microsoft and NTT Data. Can use logos of those organizations.

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE 
Please review 3 design options attached, let me know if you want to add address or slide with speakers
Here's [link to Canva](https://www.canva.com/design/DAFfUu5oS8E/hGpD8MSGLeauams-M77ZMA/edit?utm_content=DAFfUu5oS8E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Thank you


![Image](https://user-images.githubusercontent.com/69306070/230379814-63541bb0-ec77-4f57-b65c-442d00db8a5d.png)

![Image](https://user-images.githubusercontent.com/69306070/230379815-72df9b70-c994-4827-b27b-fa39e4d2a717.png)

![Image](https://user-images.githubusercontent.com/69306070/230379813-75f08aa1-706f-461c-8fa0-24de3797a523.png)
