### ISSUE TITLE
London Meetup - 2023-05-25

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#54]
_Use the issue's comments to track updates, reminders and communications. Remove/Add sections where needed._

_______________

> _EVENT DETAILS_

**MEETUP GROUP**: London
👉 EVENT: GSF London Meetup May 
:link: Event page URL
📆 Date/Time: Thursday, May 25 at 6 pm BST to 9 pm BST
👥 Capacity: @benlogan to opine 
📍 Location: @benlogan to opine

Proposed agenda

- 6:00 pm: Door opens. 
- 6.30 pm: Intro by @benlogan with a review of the past year's GSF progress? 
- 6:45 pm: talk 1 by @jawache 
- 7:15 pm: talk 2 by ? 
- 8:00 pm: Closing, networking, drinks & 🍕.

_______________

> _EVENT PREP_

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover
- [x] Include venue in MeetUp event
- [x] Publish Agenda

Extra notes:

**Comment by greenhsu123** [comment]
Proposed agenda

- 6:00 pm: Welcome- Doors open.
- 6.30 pm: Intro by UBS with a review on GSF's 1 year progress? 
- 6:45 pm: talk 1 by Asim
- 7:15 pm: talk 2 
- 8:00 pm: Closing, networking, drinks & 🍕.

**Comment by benlogan** [comment]
location definitely sorted - 5 Broadgate

capacity - we have quite a large attrium book and I guess we need to account for dropouts. I'd probably be happy with an upper limit of around 60, assuming we then get around 40. We need to factor in a number of Sustainable Technology volunteers from UBS, in addition to the GSF attendees (50/50 would be a nice mix - some of these UBS people will no doubt become future GSF meetup people!)

**Comment by benlogan** [comment]
drinks and nibbles sorted. should we get pizza too?

**Comment by benlogan** [comment]
I'm still working through lightning talks, but we have one confirmed. TBH I think that might be enough. with a bit of intro and then Asim's talk, I think that would be a nice balance between networking and talks?

**Comment by adamj89** [comment]
@benlogan re: talks. 1 is fine, 2 would be perfect? If we go with 1 then maybe we can organise a short panel / q&a

**Comment by benlogan** [comment]
Definitely - we will put some clear instructions together on what to do on arrival (+ directions). We can also have people on hand downstairs to meet and greet, plus reception are pretty good at that. I'm guessing name badges might be helpful - we can probably arrange that fairly easily.

**Comment by benlogan** [comment]
talks - I think it's quite likely we can get a second, I will ask around tomorrow. certainly we have the topics, it's just finding someone and having enough time to put a few slides together. should be fine. failing that, the one short talk can easily be made a bit longer - it's a great topic (digital detox).
