### ISSUE TITLE
Global Meetup Network Event - World Environment Day

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#58]
👥 Group: [GSF Global Pro Network](https://www.meetup.com/pro/gsf/)
👉 Title: UN Environment Day: The Green Software Revolution
✍️ Organiser contact: Adam Jackson
📆 Date: 5th June 2023
Time: 5pm UTC / 6pm BST / 10am PDT / 1pm EDT / 7pm CEST / 10.30pm IST

 

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [x] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [x] Publish event on Meetup **at least 2 weeks prior the date**
- [x] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover
- [x] Include venue in MeetUp event
- [x] Publish Agenda

Tech Logistics
- [x] Streamyard Licence Purchased
- [x] Connectivity to YT
- [x] Connectivity to Twitter
- [x] Connectivity to LinkedIn
- [x] Graphics (issue https://github.com/Green-Software-Foundation/meetup/issues/65)
- [x] Streamyard event created
- [x] Tech Runthrough Scheduled
- [x] Marketing plan in place

**Comment by adamj89** [comment]
Streamyard license being purchased.
Asim confirmed to speak. Need to source additional speakers.

**Comment by NAMRATA-WOKE** [comment]
@adamj89 let me know if you need my help reaching out to speakers. 
@Jenya-design to create design files - with and without speakers
@NAMRATA-WOKE will include the event in the May 19 newsletter -- do we want to do a stand-a-lone newsletter as well? @jawache let me know if you have any reservations

**Comment by NAMRATA-WOKE** [comment]
@ursvill Is it possible for you to attend this event so you can write an article to summarize how it all went?

**Comment by adamj89** [comment]
@tamigraph is confirmed

**Comment by NAMRATA-WOKE** [comment]
@adamj89 shall we schedule the run-through for the same day an hour before or same time the day before?

**Comment by ursvill** [comment]
@NAMRATA-WOKE @adamj89 - Absolutely, great idea. I assume we will record it as well, so I can get some quotes too. This sounds amazing!

**Comment by adamj89** [comment]
Pindy Bhullar is confirmed.

**Comment by adamj89** [comment]
First draft of meetup description:

**Do you want to know how software can help save the planet?**

Join us on UN World Environment Day 2023 (5th June) for an exclusive online event hosted by the Green Software Foundation, the global community of developers and organizations committed to making software more sustainable. Together we are building a trusted ecosystem of [people](https://greensoftware.foundation/working-groups/community), [standards](https://greensoftware.foundation/working-groups/standards), [tooling](https://greensoftware.foundation/working-groups/opensource) and [best practices](https://greensoftware.foundation/projects/software-carbon-intensity-sci-specification) for Green Software.

You’ll get to hear from some of the most influential voices in the green software movement, including

- Asim Hussain, Chairperson & Executive Director at Green Software Foundation and Director of Green Software & Ecosystems at Intel;
- Anne Currie, Chief Strategist & Tech Ethics at Container Solutions and Community Chair at Green Software Foundation;
- Tamara Kneese, User Experience Research Leader and Strategist and Lead Researcher at Green Software Foundation;
- Pindy Bhullar, ESG CTO at UBS and PhD Researcher.

They will share with you the key insights from the State of Green Software report, a comprehensive and cutting-edge study that reveals the environmental impact of software across different domains and platforms. You’ll learn about the current state of green software, the challenges and opportunities ahead, and the best practices and tools to make your code more eco-friendly.

You’ll also have the chance to participate in a lively panel discussion, where each speaker will choose one insight from the report and explain why it matters for the future of software. You’ll be able to ask your questions and share your thoughts through the live chat feature.

Don’t miss this unique opportunity to connect with other green-minded developers and discover how you can make a difference with your code. Register now and get ready for an inspiring and informative event.

**Comment by adamj89** [comment]
The event is now live on :

Meetup Global Network (Excluding Shanghai, Tokyo, Sydney and Melbourne groups as this would take place overnight).
YouTube: https://www.youtube.com/watch?v=ikW_1LWFd4Y
LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7065323295977398274 (this is a dynamic post)
Twitter (will appear at time of broadcast)

**Comment by aecurrie** [comment]
@adamj89 sorry, should have noticed earlier! Could you remove Chief Strategist from my job title at CS? Haven't done that in years ;-) Can you update to Green tech advocate at Container Solutions?

**Comment by adamj89** [comment]
> @adamj89 sorry, should have noticed earlier! Could you remove Chief Strategist from my job title at CS? Haven't done that in years ;-) Can you update to Green tech advocate at Container Solutions?

Absolutely! Updated LinkedIn, will make changes on YouTube and Meetup shortly.
