### ISSUE TITLE
Graphics for Global Meetup event 5th June

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#65]
Please can we request the following:

- [ ] Meetup card
- [ ] Social graphic
- [ ] Slide graphic
- [X] 1920x1080 background image for Streamyard (ideally abstract, no logos text or photos) -- UPDATE : not required as there are loads of suitable graphics in Canva
- [ ] 1920x1080 slide referencing event name with text "Starts Shortly"
- [ ] 1920x1080 slide referencing event name with text "The event has now ended"

Do we have any motion graphics? Not asking for these to be created but wondering what we have?

Event details here: https://github.com/Green-Software-Foundation/meetup/issues/58

Please can the following timezones be added:

10am PDT
1pm EDT
6pm BST
10.30pm IST

**Comment by Jenya-design** [comment]
Thank you @adamj89 
Could you give me more info about the speakers and sponsors / hosts?
I can see Namrata mentioned 'to create design files - with and without speakers' in event issue

I know that for some events we had the recordings with some motion graphics included in the video, but I think it wasn't in GSF general style, it was specific for the event. If it's something you need, could you ask Sean?  I think he was in contact with video team. I can create new design elemets if necessary

**Comment by adamj89** [comment]
@Jenya-design 

Here are the speakers:

- https://speakers.greensoftware.foundation/speakers/asim-hussain/ - Chairperson & Executive Director at Green Software Foundation, Director of Green Software & Ecosystems at Intel. 
- https://www.linkedin.com/in/annecurrie - Chief Strategist & Tech Ethics at Container Solutions, Community Chair at Green Software Foundation
- https://www.linkedin.com/in/tamara-kneese/ - User Experience Research Leader and Strategist, Lead Researcher at Green Software Foundation
- https://speakers.greensoftware.foundation/speakers/pindy-bhullar/ - ESG CTO at UBS, PhD Researcher

No hosts or sponsors, we are producing this event in-house. 

Don't worry about the motion graphics, we'll be fine with that we have. :)

**Comment by Jenya-design** [comment]
Thank you @adamj89 
Yes, they look ok, I can see that you already started to use one 
Though I made 2 copies in the same file and cleaned up the text styles and size a bit
Unfortunately Canva is a bit restrictive with text styles in one block, but if you need more emphasis on 'State of Green Software' I can figure something out
