### ISSUE TITLE
Meetup Promotion: Graphic Assets

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#70]
** details will go here once received**

Two main options you can choose from: 1) post on Instagram or 2) post(s) on Twitter 
Either way, we'd need to have your choice with relevant assets at the latest by March 31st
If you choose Instagram...

- Meetup has 91K followers
- 1 post only
- Feature one group within the GSF network or the entire network
- CTA will be focused on joining that one group and/or the global network
- We'd need high quality pictures of past events hosted within the GSF community, and ideally a quote from the GSF, a group leader or a member showcasing why this community is special

If you choose Twitter...

- Meetup has 68K followers, more tech-focused than Instagram
- We could do a series of Tweets 
- CTA will be focused on joining a specific event 
- I'm resharing the ideas we discussed together: 1) info-session about the certification, 2) working session to get people to complete the certification or 3) local events hosted by organizers

**Comment by adamj89** [comment]
Placing in parked and will update exact requirements ASAP

**Comment by Jenya-design** [comment]
Thank you @adamj89 
Please also give me some context, is it to promote Global Meetup event?

**Comment by adamj89** [comment]
Hi Jenya

No, it's connected to that but it's a separate campaign we will be running where Meetup.com share posts about us on their social platforms. I will loop you into the convo asap!
