### ISSUE TITLE
Review the meetup folder

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#8]
Review the official project folder and my old meetup folder
https://drive.google.com/drive/folders/1D8vUhHAfPRYXgtGvOVc6aRlOT5XdgrDk
- Meetup FAQ for event hosts (need to update this)
- Guidelines final (need to review and update)
- Guidelines v2 (check then archive)
- Meetup project plan (check then archive)
- PR FAQ - Meetup (check then archive, live version disappeared from Github)

**Comment by holanita** [comment]
Guidelines have been reviewed, will be shared with volunteers as a PDF for now.
We will likely move all relevant documents and files to the Wiki. TBD/WIP.

**Comment by holanita** [comment]
@tadanna I've finished reviewing the entire folder. Moved the outdated files to a separate doc and added a few comments for you to check some details. What we now have in the main folder is this:
- GSF Event Organizers (a.k.a. volunteer database)
- Meetup FAQ for Organizers (not shared yet, please review)
- Meetup Guidelines for Organizers (shared with some volunteers as a PDF)
- Meetup PM notes (my file with some notes from meetings and questions to discuss with ML)

Let me know if you have any questions. If everything looks good, I think we can close this GH issue.

**Comment by tadanna** [comment]
@holanita all good, thanks! closing this
