### ISSUE TITLE
2023-09-20 Green Software New York - Meetup Event 

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#80]
## Details

👥 Group: GSF - New York
👉 Title: Building, Deploying, and Measuring Energy-Efficient Digital Products.
✍️ Organiser: Peter Dushkin | Accenture
📆 Date: 20 September, 4-5pm ET
📍 Venue: Hudson Yards, 1 Manhattan West Accenture Building
 Capacity: 50 registrants

HOST: Accenture
PANELISTS: Accenture, Electricity Maps, Google, Microsoft
  
Looking to announce once we have the Green Light from Accenture, earliest first week of Sept. 

![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/3ba765db-eba4-4732-b620-150b04fe1905)

## Checklist

- [x] Date/Time for the event has been decided
- [x] Venue has been arranged
- [x] topic/format
- [x] speakers
- [x] mc
- [ ] assets
- [ ] mark
- [ ] venue

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [ ] Date locked? **before publishing the event**
- [x] Venue sourced? **before publishing the event**
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover
- [ ] Include venue in MeetUp event
- [ ] Publish Agenda

Extra notes:

**Comment by Jenya-design** [comment]
@adamj89 please review the graphic attached or [ in Canva ](https://www.canva.com/design/DAFte3AvnC4/wm4C0uxl1TFcaiQfZjPOvw/edit?utm_content=DAFte3AvnC4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/b27305e6-f614-44ee-a538-cd05ab14202c)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/298a8b86-c53c-4d1b-b572-59138c158805)
