### ISSUE TITLE
Create a new meetup group in Norway (Oslo)

### ISSUE THREAD

**Issue by guidemetothemoon** [Green-Software-Foundation/meetup#83]
Hello.

I'm not sure if you're monitoring following e-mail address: meetup@greensoftware.foundation, and I haven't found another contact details on your website so I will try and duplicate my question here instead😊 I hope that's OK, but please let me know if there's another place I should submit this question instead.

My name is Kristina Devochko, I'm a cloud engineer based in Oslo, Norway and I'm an active tech community member with a great passion for green software and sustainability in the tech industry.
I'll be happy to share more about myself if needed, but I would like to get straight to the point first😊

I was looking at GSF meetup groups around the world and I can see that Norway doesn't have one so I would love to create a meetup group here as well in order to create a safe, open and inclusive space for like-minded people to join, share knowledge, experience and kick-start discussions related to sustainability.
Is there a specific process that I should follow in order to do that so that the group will be a part of GSF meetup groups? I tried to find some details regarding that on your website but haven't found that many details regarding this unfortunately.

I would appreciate your help, links and further clarifications on this.
Thanks in advance!

**Comment by adamj89** [comment]
Hi @guidemetothemoon, I'm sorry that I missed your email. It looks like the group inbox didn't forward the email to me. I will reply to you over email if that's OK and then we can finalise details here.
