### ISSUE TITLE
Create SOGS Slide deck for September 2023 Meetups

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#94]
Create a set of slides based on the SOGS insights

Each slide to have a graphic to the left side based on the insight, with the text description of the insight (@Jenya-design could you lead on this?)
To the right an area to be left for some bullet points (@adamj89 will populate these)

https://stateof.greensoftware.foundation/insights/green-software-business-case/

**Comment by adamj89** [comment]
Here is a crude example:
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/6d7b4860-b473-4afb-a92a-17eeeee7cfb3)

**Comment by Jenya-design** [comment]
@adamj89 please review the slides
https://docs.google.com/presentation/d/1tduEoxcQy8TvEBHdZtXEDpRzZWd-eIS3Vsm7mviujgg/edit?usp=sharing
The order is the same as on [the webpage](https://stateof.greensoftware.foundation)

I used the[ social images for Insights](https://drive.google.com/drive/folders/1ANXV61Q_1k82USZ9g-yzB3hfVvbUVJkD?usp=sharing)

Let me know if you need any adjustments

**Comment by adamj89** [comment]
Hi Jenya, sorry I forgot to post here. I've already published the slides, they are great. Thank you!
