### ISSUE TITLE
2023 09 29 - GSF Brighton Meetup - Introducing Green Software

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#96]
PM is responsible for updating this issue, ensuring the details section is upto date and the checllist marked based on the comments

## Details

👥 Group: Green Software - Brighton
👉 Title: Introducing Green Software
✍️ Organiser: @ohuu @anewmandev
📆 Date: 2023-09-29
Time: 6.30pm-8pm
📍 Venue: [WRAP](https://www.google.com/maps/search/?api=1&query=50.828144%2C%20-0.141257)
83 Queens Road · Brighton
Capacity: How many people can come?

  https://www.meetup.com/gsf-brighton/events/295528842/

## Checklist

- [x] Date/Time for the event has been decided
- [x] Venue has been arranged
- [x] topic/format
- [x] speakers
- [x] mc
- [x] assets
- [ ] mark
- [ ] venu

General: 
- [x] Define event details: type, topic, audience (public, private, combo..)
- [X] Date locked? **before publishing the event**
- [X] Venue sourced? **before publishing the event**
- [X] Publish event on Meetup **at least 2 weeks prior the date**
- [X] Speaker sourced?

Meetup Page: 
- [x] Check organiser's permissions on Meetup
- [x] Event description & settings
- [x] Event Cover
- [x] Include venue in MeetUp event
- [x] Publish Agenda

Extra notes:

**Comment by Jenya-design** [comment]
@adamj89 I shared the visuals for the event in issue #97 Let me know if you need the copy here

**Comment by adamj89** [comment]
Hi Jenya, sorry I meant an event-specific card for the event page. But no worries I did one in Canva. https://www.canva.com/design/DAFtNXbU_WY/_SVTcKO_Lw7DGirvgPq1Qw/edit

Closing this issue :)

**Comment by Jenya-design** [comment]
@adamj89 please grant the access
Did you publish it already or I can tweak the design if necessary?

**Comment by Jenya-design** [comment]
@adamj89 thank you for sharing the design
It looks nice, I didn't change anything
