### ISSUE TITLE
Custom graphics for GSF Brighton Meetup

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#97]
Hi Jenya

Our Brighton meetup organisers @anewmandev @ohuu have requested some custom graphics for the GSF Brighton Group.

Firstly can we have a custom Meetup graphic a bit like the one you did for Scotland? 

The colours for Brighton are also Blue and White :) I have included some landmarks below, and please include some seagulls

![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/701d1a3d-059c-40df-806f-0d4d343ec699)
<img width="1001" alt="image" src="https://github.com/Green-Software-Foundation/meetup/assets/20337337/ab842a37-1ddd-4e4a-bc00-cb78db0f133a">

![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/d6df8abb-f265-4865-9ee4-f4f8a697c225)
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/371a19d9-3225-433d-bbaf-fb88c3652c7c)
![image](https://github.com/Green-Software-Foundation/meetup/assets/20337337/c368c9ae-1941-4e26-b326-b88923e71757)

Secondly, the organisers would like a pull-up banner. Dimensions 800x2000 for this, using a variation of the custom graphic but reorganised for a banner.

Lastly they may do some flyers/cards as well. 

Please can we request this with a deadline of 1st September.

With many thanks!

**Comment by Jenya-design** [comment]
Thank you @adamj89 
I'll start the task the task as soon as I'm back on August 27
Please check a couple of questions below:

1) This is the same Meetup cover that you requested on issue #96? You mention August 30 deadline there. Is it crusial to share the cover earlier or Sep 1 is ok for all items?

2) Pull up banner is for print,  vertical and it's 800x2000 mm size. Right?

3) Do you have the size preference for the flyer/card?

Thank you

**Comment by anewmandev** [comment]
Hello Jenya. 

Adam (Newman) from GSF Brighton here. From my POV, here are the answers to your questions...

1. Sept 1st is great. No major rush, should be plenty of time to order. 
2. I was planning to order from 85 x 206cm from VistaPrint [here](https://www.vistaprint.co.uk/signs-posters/banners/retractable-banners?swsquery=pull&querycat=search_dropdown)
3. Good question, I would lean toward small cards over flyers (see below for bit more discussion).

The priority from my side is the welcome banner. The objective there is simple and clear, it's purely a visual welcome message for the meetup e.g. "Welcome to GSF Brigton". 

I think the cards/flyers could serve a slightly different purpose that requires a bit of thought. Personally I think they should be a call to action. I am imagining one side with the GSF contact details and the other with a statement of value that represents the GSF mission. For example, lifting straight from the website "We are building a trusted ecosystem of people, standards, tooling, best practices for GREEN SOFTWARE - Join us!". Or maybe something a bit more concise (to fit on a card) but you get the idea...

Any thoughts @adamj89 @NAMRATA-WOKE? 

Adam

**Comment by NAMRATA-WOKE** [comment]
@anewmandev I love the way you're thinking and do agree that cards need to help tell the story and tease either the type of culture they will be a part of or the work they might have the opportunity to engage with. Since this is a Meetup group, another way to look at it is to give people a sense of the type of gatherings they will get to experience at every Meetup, which is a bit different than how you would think about messaging an organization. 

Here's some messaging that could work: 

Your gateway to influence standards, tooling and best practices shaping green software
Join the Movement for Sustainable Software

I think cards are better than flyers because frankly, no one keeps pamphlets or sheets of paper for too long. People hold on to cards because they signify making a connection – at least for longer than they would any other informational material. 

Hope that's helpful.

**Comment by adamj89** [comment]
Oh my! @Jenya-design I love them. On the card can we change the URL to grnsft.org/brighton? I will get the URL activated.

**Comment by Jenya-design** [comment]
Thank you @adamj89! Sure, I'll update the link

**Comment by anewmandev** [comment]
@Jenya-design Superb! All looks brilliant. Thank you very much.

**Comment by ohuu** [comment]
Wow, that's amazing @Jenya-design thanks so much for putting those together so quickly!

**Comment by Jenya-design** [comment]
@adamj89 @ohuu @anewmandev 
Thank you all! I'm very happy you like the illustration
Please check the update below. All files for print are ready, but I can't attach eps here and I'm not sure if the links will for for everyone. @adamj89 please advise the best way to share 
[All files in GSF Design folder](https://drive.google.com/drive/folders/1FPB5byEfsvqSEGHG29g0_EbRT6vn92b6?usp=sharing)

Card A6 (I used the specification from [this page](https://www.vistaprint.co.uk/marketing-materials/postcards) with 1.5mm bleeds)
Preview

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/93ca5ad5-3e49-4b09-aab6-f3fdd8a2e733)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/8499dee5-cc13-40c6-a2a8-dd6ab4722c3f)

eps for print, GSF Design 
front https://drive.google.com/file/d/1arIXT4Qpzlq1BJM8rx5fzxS85Aw5h8Wl/view?usp=drive_link
back https://drive.google.com/file/d/10rzkkzC65_BqtOgypZGxRfPqB7bFDu27/view?usp=drive_link


Pull-up banner 

Preview

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/bb3896cb-1551-4331-8657-dd3bf309cd9f)

eps for print, GSF Design  
https://drive.google.com/file/d/1fwyU26BXPKpV5JCVHWjz205HGMYuuuyY/view?usp=drive_link

**Comment by anewmandev** [comment]
Brilliant, these look fantastic - thank you. 

Have requested access to the Google Drive files. @adamj89 could you grant please? If it needs a Google Workspace plan then you can add adam@cluelight.com.

re: cards: the designs are perfect. @NAMRATA-WOKE @adamj89 I have an idea about how to give them a dedicated purpose for the local community. I am going to sanity check it with Oli tonight and then come back to you and see what you think.

**Comment by anewmandev** [comment]
Hello. 

I spoke to Oli and how does this sound...

The cards at the moment look great and I think we could match the design quality with a targeted purpose and incentive to act. Right now the URL (if they go to it) redirects to the meetup page that members likely already know about and I think that would be the end of that engagement cycle. 

I think we could improve on that in two ways
- encourage members to visit the URL with a simple call to action alongside it e.g. 'find out more about your local community and how you can take action' 
- map the URL to content that is targeted at the community members

Any thoughts at this point? 

I ran with this a little further and I am thinking of a very light welcome page specific to the local community. The purpose is to act as an entry point for the community and bridge the onboarding gap to GSF content. For example a welcome message and links to GSF content curated specific to the community (e.g. next meetup, suggest a topic/offer to speak, contact organisers, GSF educational content/articles relevant to community dialogue etc). I am keen not to get carried away before we've even started but I think something simple along these lines could help with our GSF Brighton mission: engagement, learning and action. 

Oli will knock up a quick prototype in the next few days of what we are thinking so we can show you and we can go from there. 

If you are happy then we can work out where it lives (we are happy to host it outside of GSF domains) and we could even upload the code as an open source contribution for other communities to use as a template (am sure many won't take this approach, but some might). 

Any initial thoughts? @NAMRATA-WOKE  @adamj89 

Adam

**Comment by adamj89** [comment]
Hi @anewmandev I am happy to do a different custom URL? Our number 1 priority is to get folks registered for the meetup community, second priority is getting events on the calendar. Past that I'm happy for you to set whatever priorities you like.
@Jenya-design is going to upload the designs to a public Google drive. 
@Jenya-design the design is approved from my perspective, pending amendments to URL perhaps.

**Comment by Jenya-design** [comment]
Thank you @adamj89 
@anewmandev I uploaded the designs to the public drive, please try these links

All design files - https://drive.google.com/drive/folders/1q0cMZXhL5vKc-qi_IO0fAW8jJmT8xHiy?usp=sharing

A6 card eps for print (waiting for the final URL to update the card)
front https://drive.google.com/file/d/15Hiugo7tw6xwsNtES4HIAUdNrLRfNIxv/view?usp=sharing
back https://drive.google.com/file/d/1AOCLwx4Dmm88k81yT82CsPE-OXjBvtOn/view?usp=sharing

Pull-up banner eps for print 
https://drive.google.com/file/d/1FXbv5_pfsBDNS-bnpDQps6DcxgvbSbO9/view?usp=sharing

**Comment by adamj89** [comment]
@anewmandev @ohuu are you happy with all of these? Please let me know and ensure you've got everything downloaded before I close the issue and move this to 'done' on Jenya's board.

**Comment by anewmandev** [comment]
> Hi @anewmandev I am happy to do a different custom URL? Our number 1 priority is to get folks registered for the meetup community, second priority is getting events on the calendar. Past that I'm happy for you to set whatever priorities you like.

@adamj89 makes senes - I'll drop you an email re: this stuff.

**Comment by Jenya-design** [comment]
Hi @anewmandev I'll adjust for 85x55mm size 
I picked A6 card because the illustration is rather busy, so it might look better in postcard size

**Comment by anewmandev** [comment]
Thanks @Jenya-design - that makes sense. I will print a combination of both card sizes then, really appreciate all this. Adam

**Comment by Jenya-design** [comment]
@anewmandev please check the files for business card size here 
https://drive.google.com/drive/folders/1YUBIGCji3oSsM0P-ADOJlk-5TQ062p5-?usp=sharing
eps files are for print, design is 88x59mm size (includes bleeds), final size 85x55

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/8bc48f49-31e9-4e47-81cb-9120dcb27d09)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/fe3254e9-447a-4a0e-9f84-01c526c0f324)

**Comment by anewmandev** [comment]
Thanks @Jenya-design - we're delighted with all the designs and appreciate the back and forth :) Adam
